#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"
#include "data-mov/push.h"
#include "data-mov/pop.h"
#include "data-mov/movx.h"
#include "arithmetic/add-sub.h"
#include "arithmetic/ari-misc.h"
#include "arithmetic/imul.h"
#include "logical/log.h"
#include "logical/shift.h"
#include "logical/setcc.h"
#include "logical/test.h"
#include "ctrl-trans/jcc.h"
#include "ctrl-trans/jmp.h"
#include "ctrl-trans/call.h"
#include "ctrl-trans/ret.h"
#include "flag-ctrl/flag.h"

#include "misc/misc.h"
